# Skip-gram model with Bigrams
### For more information visit the web site :https://radimrehurek.com/gensim/models/word2vec.html

In [78]:
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd
from nltk.tokenize import word_tokenize
sentences=[ "We studied 58 patients with grade 1-2 essential hypertension ( 25 men and 33 women ) , 48.7 ( 11.9 ) years of age , randomly assigned to receive torasemide ( 5 mg/day ) either upon awakening or at bedtime .  Blood pressure was measured by ambulatory monitoring for 48 consecutive hours before and after 6 weeks of therapy . Efficacy of torasemide was significantly higher with bedtime dosing ( 11.2 and 8.0 mmHg reduction in the 24-hour mean of systolic and diastolic blood pressure , respectively ) as compared to the administration of the drug on awakening ( 6.2 and 3.7 mmHg reduction in systolic and diastolic blood pressure ) . The percentage of patients with controlled ambulatory blood pressure after treatment was also higher after bedtime treatment ( 54 % versus 27 % ) . The time-response curves indicate a full 24-hour therapeutic duration only when torasemide was administered before bedtime . With regard to the safety profile , 2 patients presented secondary effects ( abdominal pain , diarrhea ) in morning dose , and 4 patients taking the drug at bedtime reported nicturia . "]
st=[]
for sent in sentences:
    tokens = word_tokenize(sent)
    tokens = [w.lower() for w in tokens]
    st.append(tokens)
print(st[0])

['we', 'studied', '58', 'patients', 'with', 'grade', '1-2', 'essential', 'hypertension', '(', '25', 'men', 'and', '33', 'women', ')', ',', '48.7', '(', '11.9', ')', 'years', 'of', 'age', ',', 'randomly', 'assigned', 'to', 'receive', 'torasemide', '(', '5', 'mg/day', ')', 'either', 'upon', 'awakening', 'or', 'at', 'bedtime', '.', 'blood', 'pressure', 'was', 'measured', 'by', 'ambulatory', 'monitoring', 'for', '48', 'consecutive', 'hours', 'before', 'and', 'after', '6', 'weeks', 'of', 'therapy', '.', 'efficacy', 'of', 'torasemide', 'was', 'significantly', 'higher', 'with', 'bedtime', 'dosing', '(', '11.2', 'and', '8.0', 'mmhg', 'reduction', 'in', 'the', '24-hour', 'mean', 'of', 'systolic', 'and', 'diastolic', 'blood', 'pressure', ',', 'respectively', ')', 'as', 'compared', 'to', 'the', 'administration', 'of', 'the', 'drug', 'on', 'awakening', '(', '6.2', 'and', '3.7', 'mmhg', 'reduction', 'in', 'systolic', 'and', 'diastolic', 'blood', 'pressure', ')', '.', 'the', 'percentage', 'of', 'pat

In [94]:
from gensim.models import Word2Vec
# train a bigrams detector.
bigram_transformer = Phrases(st,min_count=1)
modelsurv = Word2Vec(bigram_transformer[st], min_count=1,vector_size=1)
# summarize the loaded model
print(modelsurv)
# summarize vocabulary
words = list(modelsurv.wv.key_to_index)
print(words)

Word2Vec<vocab=95, vector_size=1, alpha=0.025>
['postoperatively', ',', 'patients_receiving', 'than', 'of', 'the', 'the_study', '.', 'epinephrine', 'or', 'the_treatment', 'statistically_significant', 'timing_of', '(_p', 'either', ')_.', 'no', 'consumption', 'medication_preoperatively', 'medication', 'receiving', 'at', '=', 'was', 'those', 'combination_of', 'and_epinephrine', 'as', 'scores', 'lower_pain', 'pain_control', 'bupivacaine_and', 'bupivacaine', 'patients', 'successfully', 'significantly', 'had', 'completed', 'protocol', 'combinations', 'of_morphine', '<', '.0001', 'measurement', 'yielded', 'injection', 'and', 'irrespective', 'narcotics', 'which', 'alone', 'first', 'injected', '(', 'arthroscop', 'provide', 'excellent', 'postoperative', 'when', 'used', 'preoperatively', 'in', 'knee', '._there', 't', 'a', 'trend', 'that', 'preoperative', 'analgesic', 'injections', 'experienced', 'superior', 'well', 'morphine_,', '.the', 'difference', '0', ')', 'did', '.0343', 'there_was', 'effect

In [83]:
print(modelsurv.wv['pain'])
print(modelsurv.wv.similar_by_word('pain') )


[-0.8740874]
[('randomly', 1.0), ('1-2', 1.0), ('nicturia', 1.0), ('upon', 1.0), ('mg/day', 1.0), ('5', 1.0), ('receive', 1.0), ('2', 1.0), ('grade', 1.0), ('33', 1.0)]


In [84]:
print(modelsurv.wv['randomly', '1-2', 'nicturia', 'upon', 'mg/day', '5', 'receive', '2', 'grade', '33'])


[[-0.4144957 ]
 [-0.76557475]
 [-0.41300604]
 [-0.15523957]
 [-0.35326207]
 [-0.6780844 ]
 [-0.4445696 ]
 [-0.15080094]
 [-0.8154686 ]
 [-0.4381722 ]]


In [85]:
from gensim.models import Word2Vec
modelsurv = Word2Vec(bigram_transformer[st], min_count=1,vector_size=2)
# summarize the loaded model
print(modelsurv)


Word2Vec<vocab=110, vector_size=2, alpha=0.025>


In [86]:
print(modelsurv.wv['pain'])
print(modelsurv.wv.similar_by_word('pain')  )


[-0.0344286  0.386681 ]
[('effects', 0.9998037219047546), ('secondary', 0.9995718002319336), ('48', 0.9978600144386292), ('to_the', 0.9972957372665405), ('on', 0.9919712543487549), ('2', 0.9864487648010254), ('men', 0.9799752831459045), ('years', 0.9732295274734497), ('patients', 0.964857816696167), ('assigned', 0.963462233543396)]


In [87]:
print(modelsurv.wv['effects','secondary','48', 'to_the', 'on', '2', 'men','years', 'patients','assigned'])
 

[[-0.04579268  0.41994843]
 [-0.01041142  0.17466633]
 [-0.04315702  0.27758962]
 [-0.04728323  0.2886573 ]
 [ 0.00589052  0.15493423]
 [-0.08697879  0.33556914]
 [-0.04217291  0.14170608]
 [ 0.04619973  0.32062832]
 [-0.1745979   0.4714274 ]
 [ 0.05577656  0.30247355]]


In [88]:
from gensim.models import Word2Vec
modelsurv = Word2Vec(bigram_transformer[st], min_count=1,vector_size=3)
print(modelsurv.wv['pain'])

[ 0.10921132  0.04822416 -0.02795384]


In [89]:
print(modelsurv.wv.similar_by_word('pain')  )
print(modelsurv.wv['dosing', 'randomly', 'torasemide', 'we', 'only', 'respectively', '.', '33', 'as','receive'])


[('dosing', 0.9987161159515381), ('randomly', 0.963797926902771), ('torasemide', 0.9480313062667847), ('we', 0.9432605504989624), ('only', 0.939445972442627), ('respectively', 0.897213876247406), ('.', 0.8581104278564453), ('33', 0.8520382046699524), ('as', 0.8314549922943115), ('receive', 0.8276056051254272)]
[[ 0.31974766  0.12626493 -0.09253141]
 [ 0.3003011   0.21782692 -0.0221054 ]
 [ 0.24719653  0.22078094 -0.12200838]
 [ 0.12886761  0.06717101  0.01492179]
 [ 0.2543021   0.24461922 -0.11915247]
 [ 0.27776605  0.00415853 -0.14990212]
 [ 0.21432671  0.29947424 -0.16514207]
 [ 0.22308448  0.33170563 -0.14346758]
 [ 0.18913858  0.3065405  -0.1346152 ]
 [ 0.17829235  0.2590716  -0.18962674]]


In [90]:
## PubMed_200k_RCT
import numpy as np # linear algebra
import os # accessing directory structure
import pandas as pd
from nltk.tokenize import word_tokenize
sentences=["Fifty patients successfully completed the study protocol . Patients receiving combinations of morphine  , bupivacaine , and epinephrine or bupivacaine and epinephrine yielded lower pain scores and narcotics consumption than patients receiving epinephrine alone , which was statistically significant irrespective of the timing of injection ( P < .0001 ) . 	Patients receiving the study medication preoperatively had significantly lower pain scores at the first measurement ( t = 0 ) than those receiving the study medication postoperatively ( P = .0343 ) . There was no statistically significant effect of timing of the treatment medication administration at either 60 or 120 minutes postoperatively . Comparison of fentanyl consumption between groups receiving the treatment medication preoperatively versus postoperatively showed no significant difference .The combination of morphine , bupivacaine , and epinephrine , as well as the combination of bupivacaine and epinephrine provide excellent postoperative pain control when used either preoperatively or postoperatively in knee arthroscop . There was a trend that patients receiving preoperative analgesic injections experienced superior pain control than did those injected postoperatively . "]
st=[]
for sent in sentences:
    tokens = word_tokenize(sent)
    tokens = [w.lower() for w in tokens]
    st.append(tokens)
print(st[0])


['fifty', 'patients', 'successfully', 'completed', 'the', 'study', 'protocol', '.', 'patients', 'receiving', 'combinations', 'of', 'morphine', ',', 'bupivacaine', ',', 'and', 'epinephrine', 'or', 'bupivacaine', 'and', 'epinephrine', 'yielded', 'lower', 'pain', 'scores', 'and', 'narcotics', 'consumption', 'than', 'patients', 'receiving', 'epinephrine', 'alone', ',', 'which', 'was', 'statistically', 'significant', 'irrespective', 'of', 'the', 'timing', 'of', 'injection', '(', 'p', '<', '.0001', ')', '.', 'patients', 'receiving', 'the', 'study', 'medication', 'preoperatively', 'had', 'significantly', 'lower', 'pain', 'scores', 'at', 'the', 'first', 'measurement', '(', 't', '=', '0', ')', 'than', 'those', 'receiving', 'the', 'study', 'medication', 'postoperatively', '(', 'p', '=', '.0343', ')', '.', 'there', 'was', 'no', 'statistically', 'significant', 'effect', 'of', 'timing', 'of', 'the', 'treatment', 'medication', 'administration', 'at', 'either', '60', 'or', '120', 'minutes', 'postoper

In [91]:
from gensim.models import Word2Vec
bigram_transformer = Phrases(st,min_count=1)
modelsurv = Word2Vec(bigram_transformer[st], min_count=1,vector_size=1)
# summarize the loaded model
print(modelsurv)



Word2Vec<vocab=95, vector_size=1, alpha=0.025>


### In this case the word 'pain' is not present in the model vocabulary.

In [92]:
print(modelsurv.wv['pain'])

KeyError: "Key 'pain' not present"